### ISSUE TITLE
Can't write files after receiving

### ISSUE THREAD

**Issue by pR0Ps** [psanford/wormhole-william-mobile#11]
Every time I receive a transferred file the app crashes and I see the following error in the logs:
```
java.lang.SecurityException: Unsupported path /storage/emulated/0/Download/<redacted filename>
```

Environment: v1.0.3 from the GitHub release on LineageOS 17.1 (Android 10) on a Sony Xperia XZ1C

I've also seen the app crash in the same way on a Pixel 2 running stock Android 10 but can't check the logs to verify it's the same crash (but it looks like it).

On both devices the app didn't ask for any permissions. Newer Android versions have locked down writing to the SD card more tightly so the app might need to request the storage permission in order to work. See https://developer.android.com/training/data-storage

**Comment by psanford** [comment]
This is a duplicate of issue #9. Will close this and comment there on the current state.

**Comment by pR0Ps** [comment]
Whoops, I excluded that one while looking for an existing issue solely based the title. Sorry for the noise!
