### ISSUE TITLE
Corrupt sends with v1.0.4

### ISSUE THREAD

**Issue by rboyer** [psanford/wormhole-william-mobile#15]
I was trying to use this Android tool to send a file to my Linux laptop and I'm pretty sure it's corrupting the transfer.

I have a 2,693,769 byte binary file (tgz file) that on the other side of the wormhole ends up with an extra 375 bytes of seeming garbage at the end. I tried slicing that suffix off and passing it to the Linux "file" command and it doesn't have a detected structure.

I'm wondering if there's a uninitialized buffer read or incorrectly sized buffer involved?

**Comment by psanford** [comment]
I was able to reproduce this by generating a file of that length. I'll take a closer look this evening.

**Comment by psanford** [comment]
I believe this should be fixed in 233058dc. If you are able, can you try manually installing this build to confirm that it fixes the issue for you? https://github.com/psanford/wormhole-william-mobile/releases/tag/v1.0.5rc1

**Comment by rboyer** [comment]
Works now on that previously bad file transfer

**Comment by psanford** [comment]
1.0.5 is now available on the Play Store with this fix.

Thanks again!
