### ISSUE TITLE
use regular text box for receive code and allow spaces instead of dashes

### ISSUE THREAD

**Issue by dnr** [psanford/wormhole-william-mobile#20]
I think two small changes would greatly improve usability of receiving files:

1. Make the code field a regular text box to allow swipe-typing and autocomplete. The words are all dictionary words, so this would greatly speed up entry. Even if making the change would get rid of the number bar, I think it would still be a net improvement since there's only one digit but two full words to type in the default codes.
2. Allow typing spaces instead of dashes, and just replace spaces by dashes before using the code. Typing a space is much easier than a dash on the android keyboard (in fact with swipe-typing you don't even need to explicitly type a space), and there's no reason to strictly require dashes.

**Comment by psanford** [comment]
1 will require upstream changes in [gio](https://gioui.org/). I believe these are planned, so we can revisit this when those changes land.

2. seems like a good improvement. We can probably get this into the next release.
