### ISSUE TITLE
Version 1.0.7 crashes on startup on Android

### ISSUE THREAD

**Issue by uyar** [psanford/wormhole-william-mobile#24]
I've reported this issue also using "send feedback" on my Android phone. It's a Sony Xperia F5321 phone with Android 8.0.0. Version 1.0.6 works, but 1.0.7 crashes as soon as you launch it. I will try to send the "adb logcat" output once I figure out how to do that.

**Comment by psanford** [comment]
Sorry to hear this is crashing for you. The only change that went into 1.0.7 was a UI library upgrade to get some accessibility improvements. 

I've not tested on any android version as old as you are running. When I have some time I'll see if I can get a older version running on an emulator.

**Comment by uyar** [comment]
It's no big deal. I've rolled back to 1.0.6 which works fine. Maybe I'll miss out on new features after that but it's great as it is.

**Comment by psanford** [comment]
I'd still be interested in seeing the logs for the application when it crashes. Its possible this could affect other users.

**Comment by uyar** [comment]
Posted to the wrong issue, trying again.

I'm not sure whether this is what you want or not, but here's what I've come up with:

``
--------- beginning of main
02-22 23:20:49.688 20147 20171 D OpenGLRenderer: HWUI GL Pipeline
02-22 23:20:49.697 20147     0 E Go      : panic: runtime error: index out of range [0] with length 0
02-22 23:20:49.697 20147     0 E Go      : 
02-22 23:20:49.697 20147     0 E Go      : goroutine 35 [running, locked to thread]:
02-22 23:20:49.697 20147 20165 I io.sanford.wormhole_william: panic: runtime error: index out of range [0] with length 0
02-22 23:20:49.697 20147     0 E Go      : gioui.org/io/router.(*pointerQueue).appendSemanticChildren(0x4000048e88?, {0x0?, 0x4000002680?, 0x4000048be0?}, 0x7?)
02-22 23:20:49.697 20147 20165 I io.sanford.wormhole_william: 
02-22 23:20:49.697 20147     0 E Go      :      /home/psanford/projects/go/pkg/mod/gioui.org@v0.0.0-20211226092054-3a20330d8213/io/router/pointer.go:373 +0x2c8
02-22 23:20:49.698 20147     0 E Go      : gioui.org/io/router.(*pointerQueue).AppendSemantics(0x4?, {0x0, 0x0, 0x0})
02-22 23:20:49.698 20147     0 E Go      :      /home/psanford/projects/go/pkg/mod/gioui.org@v0.0.0-20211226092054-3a20330d8213/io/router/pointer.go:349 +0x48
02-22 23:20:49.698 20147     0 E Go      : gioui.org/io/router.(*Router).AppendSemantics(...)
02-22 23:20:49.698 20147     0 E Go      :      /home/psanford/projects/go/pkg/mod/gioui.org@v0.0.0-20211226092054-3a20330d8213/io/router/router.go:186
02-22 23:20:49.698 20147     0 E Go      : gioui.org/app.(*Window).updateSemantics(0x4000194000)
02-22 23:20:49.698 20147     0 E Go      :      /home/psanford/projects/go/pkg/mod/gioui.org@v0.0.0-20211226092054-3a20330d8213/app/window.go:619 +0xac
02-22 23:20:49.698 20147     0 E Go      : gioui.org/app.(*Window).lookupSemantic(...)
02-22 23:20:49.698 20147     0 E Go      :      /home/psanford/projects/go/pkg/mod/gioui.org@v0.0.0-20211226092054-3a20330d8213/app/window.go:606
02-22 23:20:49.698 20147     0 E Go      : gioui.org/app.(*Window).run(0x4000194000, {0x400018c000, 0x3, 0x4})
02-22 23:20:49.698 20147     0 E Go      :      /home/psanford/projects/go/pkg/mod/gioui.org@v0.0.0-20211226092054-3a20330d8213/app/window.go:701 +0x914
02-22 23:20:49.698 20147     0 E Go      : created by gioui.org/app.NewWindow
02-22 23:20:49.698 20147     0 E Go      :      /home/psanford/projects/go/pkg/mod/gioui.org@v0.0.0-20211226092054-3a20330d8213/app/window.go:169 +0x620
--------- beginning of crash
02-22 23:20:49.698 20147 20164 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 20164 (ormhole_william)
``

**Comment by psanford** [comment]
This looks like a bug in gio that has since been fixed (https://todo.sr.ht/~eliasnaur/gio/328). I'll upgrade gio and cut a new rc build to test with.

**Comment by psanford** [comment]
I've published v1.0.8rc1 here: https://github.com/psanford/wormhole-william-mobile/releases/tag/v1.0.8rc1. Can you try manually installing this and see if it fixes the crash for you?

**Comment by uyar** [comment]
I've tested v1.0.8rc1. It doesn't crash. Sending and receiving text and files all work. Sharing to Wormhole William from another application also worked. The "paste from clipboard" button didn't work in both send and receive. And scanning the QR code always resulted in a " not a wormhole code" message although I've tested QR code generation with a few different apps and I'm pretty sure they're correct.

**Comment by psanford** [comment]
The paste from clipboard seems to be broken for me as well. I'll work on that.

The qr code expects a certain uri format. The easiest way to generate that is to use the wormhole-william cli tool: ```

**Comment by psanford** [comment]
I've published a new release candidate that fixes the paste issue: https://github.com/psanford/wormhole-william-mobile/releases/tag/v1.0.8rc2

Thanks again for reporting this issue and for testing the release candidate build thoroughly!

**Comment by uyar** [comment]
Everything works on version 1.0.8rc2, including QR code scanning as you have described it. I see that the QR code includes the rendezvous URL. In my tests I had only used the security code.

Glad if I could help.

**Comment by psanford** [comment]
v1.0.8 is now submitted for Play Store review. It should start going out in the next day or so on the play store.

Thanks again for the bug report and the help debugging!
