### ISSUE TITLE
Getting working on Desktop and Mobile.

### ISSUE THREAD

**Issue by gedw99** [psanford/wormhole-william-mobile#36]
Hey @psanford 

Am playing around with getting this working on Desktop and Mobile.

Would you mind letting me know your thoughts on the following ?

Any reason you don't use gioui.org/x/explorer to allow the user to pick the file they want to use ?
- https://pkg.go.dev/gioui.org/x/explorer
- example usage: https://github.com/gioui/gio-example/blob/main/explorer/main.go
- I tested the example on Desktop and Mobile and it was all good.

cheers

ged

**Comment by psanford** [comment]
The goal of this project is to support mobile devices: Android (and maybe iOS). Making a desktop application is not in scope for wormhole-william-mobile. If you are looking for a magic wormhole desktop UI, I would suggest https://github.com/Jacalz/rymdport

Of course you are also welcome to fork this repository if you are interested in creating a desktop app based on it.

**Comment by gedw99** [comment]
The explorer works on mobile too. anyways.

**Comment by gedw99** [comment]
> https://github.com/Jacalz/rymdport

Its fine, prefer gioui
