### ISSUE TITLE
Display issues in Xiaomi device

### ISSUE THREAD

**Issue by ohadlb** [psanford/wormhole-william-mobile#39]
I'm using a Xiaomi Redmi 12 running Android 14

All the text elements in the GUI are missing. This includes tab titles and crucially the send/receive codes. In the past the app displayed with no issues, so this might be related to some system update. Reinstalling the app had no effect on this issue.
The basic functionality itself still works: clicking the buttons triggers their their actions as expected and it is possible to e.g. copy send codes and paste them in another app where they can be seen.

<img src="https://github.com/user-attachments/assets/6bba7992-ac85-4443-951d-879efae41a67" alt="Screenshot of the app without visible text nodes" width="200" />

**Comment by thelazyoxymoron** [comment]
Are you by any chance using it in dark mode? I'd seen something similar happening with one of the apps I was using, and just switching off the dark mode made it alright. Give it a try once.

**Comment by ohadlb** [comment]
In my case I have the same issue both with and without dark mode.

**Comment by kmille** [comment]
I have the same problem using latest stable GrapheneOS on Pixel 6a for a some weeks. Turning off dark mode didn't help.

**Comment by psanford** [comment]
After upgrading my pixel to android 15 I'm seeing this as well. I'll try to make some time for this this weekend

**Comment by meejah** [comment]
I tried to use my GrapheneOS phone to test https://github.com/magic-wormhole/magic-wormhole/pull/555#issuecomment-2477056406 and see the same as above users.

Would be great to have interoperable QR codes across the CLI and this app! Let me know if I can help.

**Comment by meejah** [comment]
There is proposed support from the CLI client: https://github.com/magic-wormhole/magic-wormhole/pull/555#issuecomment-2477056406

**Comment by ohadlb** [comment]
Hey @psanford thanks for taking the time to work on this
I'm not familiar with mobile development but please let me know if there's any way I can help as well

**Comment by psanford** [comment]
I've pushed changes that should fix this issue. The release binary is available here: https://github.com/psanford/wormhole-william-mobile/releases/tag/v1.0.11

Please let me know if that fixes it for you.

**Comment by personalcomputer** [comment]
Thanks @psanford! Works for me.

Before: (Android 15, Wormhole William 1.0.10 (Playstore))
![Screenshot_20241130-090653](https://github.com/user-attachments/assets/6b9b95c6-0423-4eaf-a3c6-c0aafb357692)


After: (Android 15, Wormhole William 1.0.11 (APK from GitHub))
![Screenshot_20241130-090813](https://github.com/user-attachments/assets/96d5170e-5f58-4637-bffd-114be222de47)

**Comment by psanford** [comment]
Alright, all previous behavior has been restored and should be working on android 15 devices: https://github.com/psanford/wormhole-william-mobile/releases/tag/v1.0.12

I'll go ahead and release this version to the play store. Once it is rolled out I'll close this issue.

**Comment by psanford** [comment]
This is now available on the play store.

**Comment by meejah** [comment]
Reporting that on latest GrapheneOS this now works, thanks!
